### PR TITLE
[Inference] Improve the support of sentence transformers

### PR DESCRIPTION
**Pull request by JingyaHuang**
This PR aims 
* To be aligned with recent changes in Optimum main repo: https://github.com/huggingface/optimum/pull/1589
* Offer better support for sentence transformers 

It will solve reported issue: https://github.com/aws-neuron/aws-neuron-sdk/issues/808

cc. @fxmarty

-----------

[Examples]

* Encoder
```
optimum-cli export neuron -m BAAI/bge-large-en-v1.5 --sequence_length 384 --batch_size 1 --task feature-extraction bge_emb/
```

* Clip

```bash
optimum-cli export neuron -m sentence-transformers/clip-ViT-B-32 --sequence_length 64 --batch_size 1 --num_channels 3 --height 64 --width 64 --task feature-extraction --library-name sentence_transformers --subfolder 0_CLIPModel clip_emb/
```

[Inference]

```python
from transformers import AutoTokenizer
from optimum.neuron import NeuronModelForSenetenceTransformers

tokenizer = AutoTokenizer.from_pretrained("optimum/bge-base-en-v1.5-neuronx")
model = NeuronModelForSenetenceTransformers.from_pretrained("optimum/bge-base-en-v1.5-neuronx")

inputs = tokenizer("In the smouldering promise of the fall of Troy, a mythical world of gods and mortals rises from the ashes.", return_tensors="pt")

outputs = model(**inputs)
token_embeddings = outputs.token_embeddings
sentence_embedding = = outputs.sentence_embedding
```

### CODE REVIEW

**Review by dacorvo — COMMENTED** [review]
LGTM, but do we have tests for this ?

**Review by michaelbenayoun — APPROVED** [review]
LGTM

**Review by dacorvo — APPROVED** [review]
LGTM, Thanks for this pull-request !

Note: "Abandon inf1": I sympathize ... 😉

**Comment by fxmarty** [comment]
@JingyaHuang as discussed we'll find a way to stop editing `model_type` for other libraries than transformers.

**Comment by JingyaHuang** [comment]
[Heads up!]
The inference API in this PR could be unstable as we are planning some refactoring for the root exporter in Optimum main.
cc. @fxmarty @echarlaix

**Comment by austinmw** [comment]
`NeuronModelForSenetenceTransformers` -> `NeuronModelForSentenceTransformers`

**Comment by JingyaHuang** [comment]
Good catch, thanks @austinmw !

(it's what happens when we copy a long string everywhere while having a typo... 🫣)

Fix will be here: https://github.com/huggingface/optimum-neuron/pull/412

**Pull request merged**
