### PR TITLE
Update doc workflows

### PR DESCRIPTION
**Pull request by regisss**
Following https://github.com/huggingface/doc-builder/pull/379.

### CODE REVIEW

**Comment by regisss** [comment]
@michaelbenayoun @JingyaHuang

**Comment by regisss** [comment]
@michaelbenayoun @JingyaHuang Could you add me as a collaborator for this repo? I would like to check the secrets because the doc build failed.

**Comment by michaelbenayoun** [comment]
Done!

**Comment by regisss** [comment]
So it doesn't work from forks. Will work on a fix.

**Pull request merged**
