### PR TITLE
Use AWS Neuron sdk 2.18

### PR DESCRIPTION
**Pull request by dacorvo**
# What does this PR do?

This pull-request bumps the AWS Neuron SDK version to 2.18.

It also bumps the TGI router version to 1.4.4 to fix build issues due to underlying rust packages updates.

To update your local host, do the following:

```shell
$ sudo apt update
$ sudo apt install -u aws-neuronx-dkms aws-neuronx-runtime-lib aws-neuronx-collectives aws-neuronx-tools
$ pip install -U neuronx-cc torch-neuronx==1.13.* transformers-neuronx neuronx-distributed
```

### CODE REVIEW

**Comment by dacorvo** [comment]
@JingyaHuang the neuronx SD cache test is failing.

**Comment by dacorvo** [comment]
@michaelbenayoun some trainium tests are failing. It may be related to changes in the way neuronx-distributed loads weights (safetensors related error messages).

**Comment by dacorvo** [comment]
@michaelbenayoun there is a newly failing distributed test with AWS 2.18, probably after your latest changes.

**Comment by dacorvo** [comment]
No regression found but the SDXL separate weights: let's merge this !

**Review by JingyaHuang — APPROVED** [review]
LGTM, let's merge it! Thanks for taking care of the upgrade.

**Pull request merged**
